PoliScrum/Models/Proyecto.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PoliScrum.Models
{
    [Table("PST_PROYECTOS")]
    public class Proyecto
    {
        [Display(Name = "ID", ShortName = "ID")]
        public int ProyectoId { get; set; }

        [DataType(DataType.Text)]
        [StringLength(200)]
        [Display(Name = "Nombre", ShortName = "Nombre")]
        public string Nombre { get; set; }

        [Display(Name = "Estado", ShortName = "Estado")]
        public int Estado { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Fecha de Inicio", ShortName = "Fecha Inicio")]
        public DateTime FechaInicio { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Fecha de Fin", ShortName = "Fecha Fin")]
        public DateTime FechaFin { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Fecha de Fin Estimada", ShortName = "Fecha Fin Estimada")]
        public DateTime FechaFinEstimada { get; set; }
    }
}

PoliScrum/Controllers/DashboardController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PoliScrum.Models;

namespace PoliScrum.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly PoliScrumContext _context;

        public DashboardController(PoliScrumContext context)
        {
            _context = context;
        }

        // GET: Dashboard/ProductBacklog/5
        public async Task<IActionResult> ProductBacklog(int? id)
        {
            Proyecto proyecto;
            if (id == null)
            {
                proyecto = await _context.Proyectos
                .Include(m => m.ProyectoEstado)
                .Include(m => m.Sprints)
                .Include(m => m.ProductBacklog)
                .LastOrDefaultAsync(m => m.ProyectoId > 0);
            }
            else
            {
                proyecto = await _context.Proyectos
                .Include(m => m.ProyectoEstado)
                .Include(m => m.Sprints)
                .Include(m => m.ProductBacklog)
                .FirstOrDefaultAsync(m => m.ProyectoId == id);
            }

            return View(proyecto);
        }

        // GET: Dashboard/SprintBacklog/5
        public async Task<IActionResult> SprintBacklog(int? id)
        {
            Sprint sprint;
            if (id == null)
            {
                sprint = await _context.Sprints
                .Include(m => m.SprintBacklog)
                .LastOrDefaultAsync(m => m.SprintId > 0);
            }
            else
            {
                sprint = await _context.Sprints
               .Include(m => m.SprintBacklog)
               .FirstOrDefaultAsync(m => m.SprintId == id);
            }

            return View(sprint);
        }


    }
}

PoliScrum/Controllers/ProyectoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PoliScrum.Models;

namespace PoliScrum.Controllers
{
    [Authorize]
    public class ProyectoController : Controller
    {
        private readonly PoliScrumContext _context;

        public ProyectoController(PoliScrumContext context)
        {
            _context = context;
        }

        // GET: Proyecto
        public async Task<IActionResult> Index()
        {
            return View(await _context.Proyectos.Include(m => m.ProyectoEstado).ToListAsync());
        }

        // GET: Proyecto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proyecto = await _context.Proyectos
                .Include(m => m.ProyectoEstado)
                .Include(m => m.Sprints)
                .Include(m => m.ProductBacklog)
                .FirstOrDefaultAsync(m => m.ProyectoId == id);
            if (proyecto == null)
            {
                return NotFound();
            }
            
            return View(proyecto);
        }

        // GET: Proyecto/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Proyecto/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProyectoId,Nombre,FechaInicio,FechaFinEstimada,FechaFin")] Proyecto proyecto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(proyecto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(proyecto);
        }

        // GET: Proyecto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proyecto = await _context.Proyectos.FindAsync(id);
            if (proyecto == null)
            {
                return NotFound();
            }
            return View(proyecto);
        }

        // POST: Proyecto/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProyectoId,Nombre,FechaInicio,FechaFinEstimada,FechaFin")] Proyecto proyecto)
        {
            if (id != proyecto.ProyectoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(proyecto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProyectoExists(proyecto.ProyectoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(proyecto);
        }

        // GET: Proyecto/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proyecto = await _context.Proyectos
                .FirstOrDefaultAsync(m => m.ProyectoId == id);
            if (proyecto == null)
            {
                return NotFound();
            }

            return View(proyecto);
        }

        // POST: Proyecto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var proyecto = await _context.Proyectos.FindAsync(id);
            _context.Proyectos.Remove(proyecto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProyectoExists(int id)
        {
            return _context.Proyectos.Any(e => e.ProyectoId == id);
        }
    }
}

PoliScrum/Controllers/SprintController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PoliScrum.Models;

namespace PoliScrum.Controllers
{
    [Authorize]
    public class SprintController : Controller
    {
        private readonly PoliScrumContext _context;

        public SprintController(PoliScrumContext context)
        {
            _context = context;
        }

        // GET: Sprint
        public async Task<IActionResult> Index()
        {
            return View(await _context.Sprints.ToListAsync());
        }

        // GET: Sprint/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sprint = await _context.Sprints
                .Include(m => m.SprintBacklog)
                .FirstOrDefaultAsync(m => m.SprintId == id);
            if (sprint == null)
            {
                return NotFound();
            }
            
            return View(sprint);
        }

        // GET: Sprint/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Sprint/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SprintId,FechaInicio,FechaFinEstimada,DuracionEstimada,FechaFin")] Sprint sprint)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sprint);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sprint);
        }

        // GET: Sprint/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sprint = await _context.Sprints.FindAsync(id);
            if (sprint == null)
            {
                return NotFound();
            }
            return View(sprint);
        }

        // POST: Sprint/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SprintId,FechaInicio,FechaFinEstimada,DuracionEstimada,FechaFin")] Sprint sprint)
        {
            if (id != sprint.SprintId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sprint);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SprintExists(sprint.SprintId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sprint);
        }

        // GET: Sprint/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sprint = await _context.Sprints
                .FirstOrDefaultAsync(m => m.SprintId == id);
            if (sprint == null)
            {
                return NotFound();
            }

            return View(sprint);
        }

        // POST: Sprint/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sprint = await _context.Sprints.FindAsync(id);
            _context.Sprints.Remove(sprint);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SprintExists(int id)
        {
            return _context.Sprints.Any(e => e.SprintId == id);
        }
    }
}

PoliScrum/Controllers/UserStoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PoliScrum.Models;

namespace PoliScrum.Controllers
{
    public class UserStoryController : Controller
    {
        private readonly PoliScrumContext _context;

        public UserStoryController(PoliScrumContext context)
        {
            _context = context;
        }

        // GET: UserStory
        public async Task<IActionResult> Index()
        {
            return View(await _context.UserStories.ToListAsync());
        }

        // GET: UserStory/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userStory = await _context.UserStories
                .FirstOrDefaultAsync(m => m.UserStoryId == id);
            if (userStory == null)
            {
                return NotFound();
            }

            return View(userStory);
        }

        // GET: UserStory/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UserStory/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserStoryId,Titulo,Descripcion,CriteriosAceptacion,OrdenPrioridad,DuracionEstimada,Valor,FechaInicio,FechaFin")] UserStory userStory)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userStory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(userStory);
        }

        // GET: UserStory/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userStory = await _context.UserStories.FindAsync(id);
            if (userStory == null)
            {
                return NotFound();
            }
            return View(userStory);
        }

        // POST: UserStory/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserStoryId,Titulo,Descripcion,CriteriosAceptacion,OrdenPrioridad,DuracionEstimada,Valor,FechaInicio,FechaFin")] UserStory userStory)
        {
            if (id != userStory.UserStoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userStory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserStoryExists(userStory.UserStoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(userStory);
        }

        // GET: UserStory/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userStory = await _context.UserStories
                .FirstOrDefaultAsync(m => m.UserStoryId == id);
            if (userStory == null)
            {
                return NotFound();
            }

            return View(userStory);
        }

        // POST: UserStory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userStory = await _context.UserStories.FindAsync(id);
            _context.UserStories.Remove(userStory);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserStoryExists(int id)
        {
            return _context.UserStories.Any(e => e.UserStoryId == id);
        }
    }
}

PoliScrum/Views/Proyecto/Create.cshtml
@model PoliScrum.Models.Proyecto

@{
    ViewData["Title"] = "Crear Nuevo";
}

<h2>Crear Nuevo</h2>

<h4>Proyecto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaInicio" class="control-label"></label>
                <input asp-for="FechaInicio" class="form-control" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFin" class="control-label"></label>
                <input asp-for="FechaFin" class="form-control" />
                <span asp-validation-for="FechaFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFinEstimada" class="control-label"></label>
                <input asp-for="FechaFinEstimada" class="form-control" />
                <span asp-validation-for="FechaFinEstimada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PoliScrum/Views/Proyecto/Delete.cshtml
@model PoliScrum.Models.Proyecto

@{
    ViewData["Title"] = "Borrar";
}

<h2>Borrar</h2>

<h3>¿Estás seguro que querés borrar este registro?</h3>
<div>
    <h4>Proyecto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaFin)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaFin)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaFinEstimada)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaFinEstimada)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProyectoId" />
        <input type="submit" value="Borrar" class="btn btn-default" /> |
        <a asp-action="Index">Volver a la Lista</a>
    </form>
</div>

PoliScrum/Views/Proyecto/Details.cshtml
@model PoliScrum.Models.Proyecto

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Proyecto</h4>    
    <hr />
    <a asp-controller="Dashboard" asp-action="ProductBacklog" asp-route-id="@Model.ProyectoId"><button type="button" class="btn btn-sm">Dashboard</button></a>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProyectoEstado)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProyectoEstado.Descripcion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaFinEstimada)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaFinEstimada)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaFin)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaFin)
        </dd>
    </dl>

    <h5>Sprints</h5>
    <hr />
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Fecha Inicio</th>
                    <th>Fecha Fin Estimada</th>
                    <th>Duración Estimada</th>
                    <th>Fecha Fin</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Sprints) {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.SprintId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FechaInicio)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FechaFinEstimada)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DuracionEstimada)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FechaFin)
                        </td>
                        <td>
                            <a asp-controller="Sprint" asp-action="Edit" asp-route-id="@item.SprintId"><span class="fas fa-edit"></span></a> |
                            <a asp-controller="Sprint" asp-action="Details" asp-route-id="@item.SprintId"><span class="fas fa-file-alt"></span></a> |
                            <a asp-controller="Sprint" asp-action="Delete" asp-route-id="@item.SprintId"><span class="fas fa-trash"></span></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <h5>Product Backlog</h5>
    <hr />
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Título</th>
                    <th>Prioridad</th>
                    <th>Fecha Inicio</th>
                    <th>Fecha Fin</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ProductBacklog) {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.UserStoryId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Titulo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.OrdenPrioridad)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FechaInicio)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FechaFin)
                        </td>
                        <td>
                            <a asp-controller="UserStory" asp-action="Edit" asp-route-id="@item.UserStoryId"><span class="fas fa-edit"></span></a> |
                            <a asp-controller="UserStory" asp-action="Details" asp-route-id="@item.UserStoryId"><span class="fas fa-file-alt"></span></a> |
                            <a asp-controller="UserStory" asp-action="Delete" asp-route-id="@item.UserStoryId"><span class="fas fa-trash"></span></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ProyectoId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PoliScrum/Views/Proyecto/Edit.cshtml
@model PoliScrum.Models.Proyecto

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Proyecto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProyectoId" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaInicio" class="control-label"></label>
                <input asp-for="FechaInicio" class="form-control" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFinEstimada" class="control-label"></label>
                <input asp-for="FechaFinEstimada" class="form-control" />
                <span asp-validation-for="FechaFinEstimada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFin" class="control-label"></label>
                <input asp-for="FechaFin" class="form-control" />
                <span asp-validation-for="FechaFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PoliScrum/Views/Proyecto/Index.cshtml
@model IEnumerable<PoliScrum.Models.Proyecto>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProyectoEstado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaInicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaFinEstimada)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaFin)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProyectoEstado.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaInicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaFinEstimada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaFin)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ProyectoId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ProyectoId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ProyectoId">Delete</a> |
                <a asp-controller="Dashboard" asp-action="ProductBacklog" asp-route-id="@item.ProyectoId"><span class="fas fa-chart-line"></span></a>
            </td>
        </tr>
}
    </tbody>
</table>